[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[context.production]
  [context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview]
  [context.deploy-preview.environment]
    NODE_ENV = "production"

[dev]
  command = "npm run dev"
  targetPort = 3000
