import { httpJson, httpRequest, bearerAuth } from "@/lib/marketplace/http";
import { downloadMarketplaceMedia } from "@/lib/marketplace/media-transfer";
import { makeDraftSettingGroup, parseEbayDefaultPolicyIds, resolveDraftSettings, type DraftSettings, type DraftSettingGroup } from "@/lib/marketplace/draft-settings";
import { EBAY_INVENTORY_WRITE_SCOPE, hasOAuthScope, resolveOAuthScopes } from "@/lib/marketplace/scopes";
import type { MarketplaceConnector, MarketplaceOAuthResult, MarketplaceConnectionContext } from "@/lib/marketplace/connector";
import type {
  NormalizedListing,
  NormalizedOrder,
  NormalizedOrderItem,
  ListingSyncParams,
  OrderSyncParams,
} from "@/lib/marketplace/types";
import {
  getValidAccessToken,
  updateTokens,
  isEncryptionReady,
  loadTokens,
} from "@/lib/marketplace/oauth";

const SCOPES = [
  "https://api.ebay.com/oauth/api_scope",
  "https://api.ebay.com/oauth/api_scope/sell.inventory",
  "https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly",
  "https://api.ebay.com/oauth/api_scope/sell.account.readonly",
].join(" ");

function env(name: string): string {
  return (process.env[name] || "").trim();
}

/**
 * eBay calls this value `redirect_uri`, but it is not a URL. It is the
 * OAuth-enabled RuName generated by eBay for the selected environment.
 */
export function getEbayConfigurationError(): string | null {
  const clientId = env("EBAY_CLIENT_ID");
  const clientSecret = env("EBAY_CLIENT_SECRET");
  const ruName = env("EBAY_RU_NAME");

  if (!clientId || !clientSecret || !ruName) {
    return "EBAY_CLIENT_ID, EBAY_CLIENT_SECRET, and EBAY_RU_NAME must be configured.";
  }
  if (/^https?:\/\//i.test(ruName)) {
    return "EBAY_RU_NAME must be the OAuth-enabled eBay RuName, not an Accept/Decline callback URL. Configure the callback URL in eBay's RuName settings.";
  }
  return null;
}

function isSandbox(): boolean {
  return env("EBAY_ENVIRONMENT").toLowerCase() === "sandbox";
}

function bases() {
  const sandbox = isSandbox();
  return {
    sandbox,
    authBase: sandbox ? "https://auth.sandbox.ebay.com" : "https://auth.ebay.com",
    apiBase: sandbox ? "https://api.sandbox.ebay.com" : "https://api.ebay.com",
    findingBase: sandbox ? "https://svcs.sandbox.ebay.com" : "https://svcs.ebay.com",
  };
}

export type EbayMarketplaceDraftInput = {
  draftSettings?: DraftSettings;
  sku: string;
  title: string;
  description: string;
  categoryId: string;
  marketplaceId: string;
  price: number;
  currency: string;
  quantity: number;
  condition: string;
  aspects: Record<string, string[]>;
  media: Array<{ mediaUrl: string; type: "IMAGE" | "VIDEO" }>;
};

type EbayBusinessPolicy = {
  name?: string;
  fulfillmentPolicyId?: string;
  paymentPolicyId?: string;
  returnPolicyId?: string;
  categoryTypes?: Array<{ default?: boolean; name?: string }>;
};

export class EbayConnector implements MarketplaceConnector {
  readonly platform = "EBAY" as const;

  private get clientId() {
    return env("EBAY_CLIENT_ID");
  }
  private get clientSecret() {
    return env("EBAY_CLIENT_SECRET");
  }
  private get ruName() {
    return env("EBAY_RU_NAME");
  }

  async isConfigured(): Promise<boolean> {
    return getEbayConfigurationError() === null;
  }

  async getAuthorizationUrl(state: string): Promise<string> {
    const { authBase } = bases();
    const params = new URLSearchParams({
      client_id: this.clientId,
      response_type: "code",
      redirect_uri: this.ruName,
      scope: SCOPES,
      state,
      // Do not silently reuse an unrelated eBay browser session. Showing the
      // eBay sign-in/consent screen makes account selection explicit.
      prompt: "login",
    });
    return `${authBase}/oauth2/authorize?${params.toString()}`;
  }

  async exchangeAuthorizationCode(code: string): Promise<MarketplaceOAuthResult> {
    if (!(await isEncryptionReady())) {
      throw new Error("Secret encryption key is not configured; cannot store eBay tokens.");
    }
    const { apiBase } = bases();
    const body = new URLSearchParams({
      grant_type: "authorization_code",
      code,
      redirect_uri: this.ruName,
    });
    const basic = Buffer.from(`${this.clientId}:${this.clientSecret}`).toString("base64");
    const data = await httpJson<Record<string, any>>(
      `${apiBase}/identity/v1/oauth2/token`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
          Authorization: `Basic ${basic}`,
        },
        body: body.toString(),
      }
    );
    const tokens = {
      accessToken: data.access_token,
      refreshToken: data.refresh_token,
      expiresAt: data.expires_in ? new Date(Date.now() + data.expires_in * 1000).toISOString() : null,
      scope: resolveOAuthScopes(data.scope, SCOPES),
    };
    const profile = await this.getAuthenticatedSeller(tokens.accessToken, apiBase);
    const externalAccountId = profile.userId;
    const accountName = profile.username || externalAccountId;
    return {
      externalAccountId,
      accountName,
      tokens,
      shops: [{ externalShopId: externalAccountId, name: accountName }],
    };
  }

  /**
   * The Sell Account API has no /user endpoint. GetUser is the supported
   * authenticated eBay API call for obtaining the account that granted OAuth.
   */
  private async getAuthenticatedSeller(accessToken: string, apiBase: string): Promise<{ userId: string; username: string | null }> {
    const response = await fetch(`${apiBase}/ws/api.dll`, {
      method: "POST",
      headers: {
        "Content-Type": "text/xml",
        "X-EBAY-API-CALL-NAME": "GetUser",
        "X-EBAY-API-COMPATIBILITY-LEVEL": "1231",
        "X-EBAY-API-SITEID": "0",
        "X-EBAY-API-IAF-TOKEN": accessToken,
      },
      body: '<?xml version="1.0" encoding="utf-8"?><GetUserRequest xmlns="urn:ebay:apis:eBLBaseComponents"><DetailLevel>ReturnAll</DetailLevel></GetUserRequest>',
    });
    const xml = await response.text();
    const userId = xml.match(/<UserID>([^<]+)<\/UserID>/i)?.[1]?.trim();

    if (!response.ok || !userId) {
      const ebayMessage = xml.match(/<(?:LongMessage|ShortMessage)>([^<]+)<\/(?:LongMessage|ShortMessage)>/i)?.[1]?.trim();
      throw new Error(ebayMessage || "eBay did not return a seller account ID after authorization.");
    }

    return { userId, username: userId };
  }

  private async getAccessToken(connectionId: string): Promise<string> {
    return getValidAccessToken(connectionId, (tokens) =>
      this.refreshAccessToken(connectionId, tokens.refreshToken!, tokens.scope)
    );
  }

  async getCategoryAspects(
    connectionId: string,
    categoryPath: string,
    marketplaceId = "EBAY_US",
    requestedCategoryId?: string
  ): Promise<{
    marketplaceId: string;
    categoryId: string | null;
    categoryPath: string | null;
    suggestions: Array<{ categoryId: string; categoryPath: string }>;
    requiredAspects: Array<{
      name: string;
      mode: string;
      values: string[];
      cardinality: string | null;
    }>;
    optionalAspects: Array<{
      name: string;
      mode: string;
      values: string[];
      cardinality: string | null;
    }>;
  }> {
    const token = await this.getAccessToken(connectionId);
    const headers = this.getHeaders(token);
    const { apiBase } = bases();
    const tree = await httpJson<{ categoryTreeId?: number | string }>(
      `${apiBase}/commerce/taxonomy/v1/get_default_category_tree_id?marketplace_id=${encodeURIComponent(marketplaceId)}`,
      { headers }
    );
    if (tree.categoryTreeId == null) throw new Error("eBay did not return a category tree for the selected marketplace.");

    const targetName = categoryPath.split(">").at(-1)?.trim();
    if (!targetName) throw new Error("A category path is required to resolve eBay listing requirements.");
    const suggestionsResponse = await httpJson<{
      categorySuggestions?: Array<{
        category?: { categoryId?: string; categoryName?: string };
        categoryTreeNode?: {
          category?: { categoryId?: string; categoryName?: string };
          categoryTreeNodeAncestors?: Array<{ categoryName?: string }>;
        };
      }>;
    }>(
      `${apiBase}/commerce/taxonomy/v1/category_tree/${encodeURIComponent(String(tree.categoryTreeId))}/get_category_suggestions?q=${encodeURIComponent(targetName)}`,
      { headers }
    );
    const suggestions = (suggestionsResponse.categorySuggestions || []).flatMap((suggestion) => {
      const category = suggestion.categoryTreeNode?.category || suggestion.category;
      if (!category?.categoryId || !category.categoryName) return [];
      const ancestors = suggestion.categoryTreeNode?.categoryTreeNodeAncestors || [];
      const path = [...ancestors.map((ancestor) => ancestor.categoryName).filter((name): name is string => Boolean(name)), category.categoryName].join(" > ");
      return [{ categoryId: String(category.categoryId), categoryPath: path }];
    });
    const normalizePath = (value: string) => value.toLowerCase().replace(/\s+/g, " ").replace(/\s*>\s*/g, ">");
    const exactPathMatch = suggestions.find((suggestion) => normalizePath(suggestion.categoryPath) === normalizePath(categoryPath));
    const leafMatches = suggestions.filter((suggestion) =>
      normalizePath(suggestion.categoryPath) === normalizePath(targetName)
    );
    const matched = (requestedCategoryId
      ? suggestions.find((suggestion) => suggestion.categoryId === requestedCategoryId)
      : undefined) || exactPathMatch || (leafMatches.length === 1 ? leafMatches[0] : undefined);
    if (requestedCategoryId && !matched) {
      throw new Error("The selected eBay category was not returned by the current Taxonomy API response.");
    }
    if (!matched) {
      return {
        marketplaceId,
        categoryId: null,
        categoryPath: null,
        suggestions,
        requiredAspects: [],
        optionalAspects: [],
      };
    }

    const aspectResponse = await httpJson<{
      aspects?: Array<{
        localizedAspectName?: string;
        aspectConstraint?: {
          aspectRequired?: boolean;
          aspectMode?: string;
          itemToAspectCardinality?: string;
        };
        aspectValues?: Array<{ localizedValue?: string }>;
      }>;
    }>(
      `${apiBase}/commerce/taxonomy/v1/category_tree/${encodeURIComponent(String(tree.categoryTreeId))}/get_item_aspects_for_category?category_id=${encodeURIComponent(matched.categoryId)}`,
      { headers }
    );

    const aspects = (aspectResponse.aspects || []).map((aspect) => ({
      name: aspect.localizedAspectName || "Unnamed aspect",
      mode: aspect.aspectConstraint?.aspectMode || "FREE_TEXT",
      values: (aspect.aspectValues || [])
        .map((value) => value.localizedValue)
        .filter((value): value is string => Boolean(value)),
      cardinality: aspect.aspectConstraint?.itemToAspectCardinality || null,
      required: Boolean(aspect.aspectConstraint?.aspectRequired),
    }));

    return {
      marketplaceId,
      categoryId: matched.categoryId,
      categoryPath: matched.categoryPath,
      suggestions,
      requiredAspects: aspects.filter((aspect) => aspect.required).map((aspect) => ({
        name: aspect.name,
        mode: aspect.mode,
        values: aspect.values,
        cardinality: aspect.cardinality,
      })),
      optionalAspects: aspects.filter((aspect) => !aspect.required).map((aspect) => ({
        name: aspect.name,
        mode: aspect.mode,
        values: aspect.values,
        cardinality: aspect.cardinality,
      })),
    };
  }

  private async refreshAccessToken(connectionId: string, refreshToken: string, scope?: string | null): Promise<string> {
    const { apiBase } = bases();
    const basic = Buffer.from(`${this.clientId}:${this.clientSecret}`).toString("base64");
    const body = new URLSearchParams({ grant_type: "refresh_token", refresh_token: refreshToken });
    const data = await httpJson<Record<string, any>>(
      `${apiBase}/identity/v1/oauth2/token`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
          Authorization: `Basic ${basic}`,
        },
        body: body.toString(),
      }
    );
    await updateTokens(connectionId, {
      accessToken: data.access_token,
      refreshToken: data.refresh_token || refreshToken,
      expiresAt: data.expires_in ? new Date(Date.now() + data.expires_in * 1000).toISOString() : null,
      scope: resolveOAuthScopes(data.scope, scope),
    });
    return data.access_token;
  }

  async ensureInventoryWriteScope(connectionId: string, storedScope?: string | null): Promise<boolean> {
    if (storedScope != null) return hasOAuthScope(storedScope, EBAY_INVENTORY_WRITE_SCOPE);
    // Older connections lost their scope because eBay omits it from token
    // responses. Ask eBay about the current token instead of assuming access.
    const accessToken = await this.getAccessToken(connectionId);
    const tokens = await loadTokens(connectionId);
    if (!tokens) throw new Error("The eBay connection has no saved OAuth token. Reconnect the shop.");
    if (tokens.scope != null) return hasOAuthScope(tokens.scope, EBAY_INVENTORY_WRITE_SCOPE);
    const { apiBase } = bases();
    const grant = await httpJson<{ active?: boolean; scope?: string }>(
      `${apiBase}/identity/v1/oauth2/token/introspect`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
          Authorization: `Basic ${Buffer.from(`${this.clientId}:${this.clientSecret}`).toString("base64")}`,
        },
        body: new URLSearchParams({ token: accessToken, token_type_hint: "access_token" }).toString(),
      }
    );
    if (!grant.active || typeof grant.scope !== "string") {
      throw new Error("eBay could not verify the connection's listing permissions. Reconnect the shop.");
    }
    await updateTokens(connectionId, { ...tokens, accessToken, scope: grant.scope });
    return hasOAuthScope(grant.scope, EBAY_INVENTORY_WRITE_SCOPE);
  }

  private getHeaders(token: string): Record<string, string> {
    return {
      ...bearerAuth(token),
      Accept: "application/json",
      "Accept-Language": "en-US",
      "Content-Language": "en-US",
    };
  }

  async getDraftSettingGroups(connectionId: string, marketplaceId = "EBAY_US"): Promise<DraftSettingGroup[]> {
    const token = await this.getAccessToken(connectionId);
    const headers = this.getHeaders(token);
    const { apiBase } = bases();
    const [fulfillmentResponse, paymentResponse, returnResponse] = await Promise.all([
      httpJson<{ fulfillmentPolicies?: EbayBusinessPolicy[] }>(
        `${apiBase}/sell/account/v1/fulfillment_policy?marketplace_id=${encodeURIComponent(marketplaceId)}`,
        { headers }
      ),
      httpJson<{ paymentPolicies?: EbayBusinessPolicy[] }>(
        `${apiBase}/sell/account/v1/payment_policy?marketplace_id=${encodeURIComponent(marketplaceId)}`,
        { headers }
      ),
      httpJson<{ returnPolicies?: EbayBusinessPolicy[] }>(
        `${apiBase}/sell/account/v1/return_policy?marketplace_id=${encodeURIComponent(marketplaceId)}`,
        { headers }
      ),
    ]);
    const preferences = await this.callTradingApi("GetUserPreferences", token, apiBase,
      '<GetUserPreferencesRequest xmlns="urn:ebay:apis:eBLBaseComponents"><ShowSellerProfilePreferences>true</ShowSellerProfilePreferences></GetUserPreferencesRequest>'
    ).catch(() => "");
    const defaults = parseEbayDefaultPolicyIds(preferences);
    const group = (key: "fulfillmentPolicyId" | "paymentPolicyId" | "returnPolicyId", label: string, policies: EbayBusinessPolicy[] = []) => {
      const eligible = policies.filter((policy) => !policy.categoryTypes?.length || policy.categoryTypes.some((type) => !type.name || type.name === "ALL_EXCLUDING_MOTORS_VEHICLES"));
      const options = eligible.flatMap((policy) => policy[key] ? [{ id: policy[key]!, name: policy.name || `${label} ${policy[key]}` }] : []);
      const legacyDefault = eligible.find((policy) => policy.categoryTypes?.some((type) => type.default))?.[key];
      return makeDraftSettingGroup(key, label, options, defaults[key] || legacyDefault);
    };
    return [
      group("fulfillmentPolicyId", "Shipping policy", fulfillmentResponse.fulfillmentPolicies),
      group("paymentPolicyId", "Payment policy", paymentResponse.paymentPolicies),
      group("returnPolicyId", "Return policy", returnResponse.returnPolicies),
    ];
  }

  async createMarketplaceDraft(
    connectionId: string,
    input: EbayMarketplaceDraftInput
  ): Promise<{ offerId: string; uploadedMedia: number; warnings: string[]; draftSettings: DraftSettings }> {
    const draftSettings = resolveDraftSettings(await this.getDraftSettingGroups(connectionId, input.marketplaceId), input.draftSettings);
    const token = await this.getAccessToken(connectionId);
    const headers = this.getHeaders(token);
    const { apiBase } = bases();

    const videoIds: string[] = [];
    const warnings: string[] = [];
    let uploadedMedia = 0;
    for (const [index, asset] of input.media.entries()) {
      if (asset.type === "IMAGE") {
        uploadedMedia += 1;
        continue;
      }
      try {
        const file = await downloadMarketplaceMedia(asset.mediaUrl, "VIDEO", 150 * 1024 * 1024);
        const mediaBase = `${apiBase}/commerce/media/v1`;
        const createdVideo = await httpRequest(
          `${mediaBase}/video`,
          {
            method: "POST",
            headers: { ...headers, "Content-Type": "application/json" },
            body: JSON.stringify({
              title: `${input.title} video ${index + 1}`,
              size: file.buffer.length,
              classification: "ITEM",
            }),
          }
        );
        const videoLocation = createdVideo.headers.get("location");
        const videoId = videoLocation?.split("/").filter(Boolean).pop();
        if (!videoId) throw new Error("eBay did not return a video ID for the selected product video.");
        await httpRequest(`${mediaBase}/video/${encodeURIComponent(videoId)}/upload`, {
          method: "POST",
          headers: { ...headers, "Content-Type": "application/octet-stream" },
          body: Uint8Array.from(file.buffer),
        });
        videoIds.push(videoId);
        uploadedMedia += 1;
      } catch (error) {
        warnings.push(`Video ${index + 1}: ${error instanceof Error ? error.message : "upload failed"}`);
      }
    }

    const imageUrls = input.media.filter((asset) => asset.type === "IMAGE").map((asset) => asset.mediaUrl);
    await httpRequest(
      `${apiBase}/sell/inventory/v1/inventory_item/${encodeURIComponent(input.sku)}`,
      {
        method: "PUT",
        headers: { ...headers, "Content-Type": "application/json", "Content-Language": "en-US" },
        body: JSON.stringify({
          availability: { shipToLocationAvailability: { quantity: input.quantity } },
          condition: input.condition,
          product: {
            title: input.title,
            description: input.description,
            imageUrls,
            videoIds,
            aspects: input.aspects,
          },
        }),
      }
    );
    const offer = await httpJson<{ offerId?: string }>(
      `${apiBase}/sell/inventory/v1/offer`,
      {
        method: "POST",
        headers: { ...headers, "Content-Type": "application/json", "Content-Language": "en-US" },
        body: JSON.stringify({
          sku: input.sku,
          marketplaceId: input.marketplaceId,
          format: "FIXED_PRICE",
          availableQuantity: input.quantity,
          categoryId: input.categoryId,
          listingDescription: input.description,
          listingPolicies: {
            fulfillmentPolicyId: draftSettings.fulfillmentPolicyId,
            paymentPolicyId: draftSettings.paymentPolicyId,
            returnPolicyId: draftSettings.returnPolicyId,
          },
          pricingSummary: { price: { value: input.price.toFixed(2), currency: input.currency } },
        }),
      }
    );
    if (!offer.offerId) throw new Error("eBay accepted the offer but did not return a draft ID.");
    return { offerId: offer.offerId, uploadedMedia, warnings, draftSettings };
  }

  async fetchListings(params: ListingSyncParams, context: MarketplaceConnectionContext): Promise<NormalizedListing[]> {
    const token = await this.getAccessToken(context.connectionId);
    const pageSize = params.limit && params.limit > 0 ? Math.min(params.limit, 100) : 100;
    const page = Math.floor((params.offset || 0) / pageSize) + 1;
    const { apiBase } = bases();
    const xml = await this.callTradingApi(
      "GetMyeBaySelling",
      token,
      apiBase,
      `<GetMyeBaySellingRequest xmlns="urn:ebay:apis:eBLBaseComponents"><DetailLevel>ReturnAll</DetailLevel><ActiveList><Include>true</Include><Pagination><EntriesPerPage>${pageSize}</EntriesPerPage><PageNumber>${page}</PageNumber></Pagination></ActiveList></GetMyeBaySellingRequest>`
    );
    const items = parseEbayActiveListings(xml);
    console.log(`[ebay] GetMyeBaySelling: shop=${context.externalShopId}, page=${page}, items=${items.length}`);

    return items.map((item) => ({
      ...item,
      marketplaceShopId: context.shopId,
      externalShopId: context.externalShopId,
      shopName: context.shopName,
    }));
  }

  private async callTradingApi(callName: string, accessToken: string, apiBase: string, body: string): Promise<string> {
    const response = await fetch(`${apiBase}/ws/api.dll`, {
      method: "POST",
      headers: {
        "Content-Type": "text/xml",
        "X-EBAY-API-CALL-NAME": callName,
        "X-EBAY-API-COMPATIBILITY-LEVEL": "1231",
        "X-EBAY-API-SITEID": "0",
        "X-EBAY-API-IAF-TOKEN": accessToken,
      },
      body: `<?xml version="1.0" encoding="utf-8"?>${body}`,
    });
    const xml = await response.text();
    const ebayMessage = xml.match(/<(?:LongMessage|ShortMessage)>([^<]+)<\/(?:LongMessage|ShortMessage)>/i)?.[1]?.trim();
    if (!response.ok || /<Ack>(?:Failure|PartialFailure)<\/Ack>/i.test(xml)) {
      throw new Error(ebayMessage || `eBay ${callName} failed (HTTP ${response.status}).`);
    }
    return xml;
  }


  async fetchOrders(params: OrderSyncParams, context: MarketplaceConnectionContext): Promise<NormalizedOrder[]> {
    const token = await this.getAccessToken(context.connectionId);
    const headers = this.getHeaders(token);
    const { apiBase } = bases();

    const pageSize = params.limit && params.limit > 0 ? params.limit : 50;
    const offset = params.offset || 0;
    const filter = params.from ? `creationdate:[${params.from}..]` : undefined;
    const query = new URLSearchParams({ limit: String(pageSize), offset: String(offset) });
    if (filter) query.set("filter", filter);

    const data = await httpJson<{ orders?: any[] }>(
      `${apiBase}/sell/fulfillment/v1/order?${query.toString()}`,
      { headers }
    );

    // Fulfillment's order search is intrinsically limited to the seller who
    // granted this connection's OAuth token; it cannot return another shop's
    // orders. Load package details separately so tracking is kept current.
    return Promise.all((data.orders || []).map(async (order) => {
      const tracking = await this.getTrackingDetails(order, headers, apiBase);
      return {
        ...this.normalizeOrder(order, tracking),
        marketplaceShopId: context.shopId,
        externalShopId: context.externalShopId,
        shopName: context.shopName,
      };
    }));
  }

  private async getTrackingDetails(
    order: any,
    headers: Record<string, string>,
    apiBase: string
  ): Promise<{ trackingCode: string | null; carrier: string | null }> {
    const id = String(order?.orderId || "").trim();
    let tracking = extractEbayShipmentTracking(order);
    if (!id || (tracking.trackingCode && tracking.carrier)) return tracking;

    const fulfillmentHrefs = new Set<unknown>(
      Array.isArray(order?.fulfillmentHrefs) ? order.fulfillmentHrefs : []
    );
    try {
      const fulfillments = await this.readJson(
        `${apiBase}/sell/fulfillment/v1/order/${encodeURIComponent(id)}/shipping_fulfillment`,
        headers
      );
      tracking = mergeEbayTracking(extractEbayShipmentTracking(fulfillments), tracking);
      if (Array.isArray(fulfillments?.fulfillmentHrefs)) {
        for (const href of fulfillments.fulfillmentHrefs) fulfillmentHrefs.add(href);
      }
    } catch (error) {
      console.warn(`[ebay] Could not load shipping fulfillments for order ${id}:`, error);
    }

    if (tracking.trackingCode && tracking.carrier) return tracking;

    for (const href of fulfillmentHrefs) {
      if (typeof href !== "string" || !href.trim()) continue;
      let url: URL;
      try {
        url = new URL(href, apiBase);
      } catch {
        console.warn(`[ebay] Ignoring invalid fulfillment link for order ${id}.`);
        continue;
      }
      if (url.origin !== new URL(apiBase).origin) {
        console.warn(`[ebay] Ignoring fulfillment link outside the eBay API for order ${id}.`);
        continue;
      }
      try {
        const fulfillment = await this.readJson(url.toString(), headers);
        tracking = mergeEbayTracking(extractEbayShipmentTracking(fulfillment), tracking);
        if (tracking.trackingCode && tracking.carrier) return tracking;
      } catch (error) {
        console.warn(`[ebay] Could not load a fulfillment link for order ${id}:`, error);
      }
    }
    return tracking;
  }

  private async readJson(url: string, headers: Record<string, string>): Promise<any> {
    const response = await httpRequest(url, { headers });
    if (response.status === 204) return {};
    const text = await response.text();
    if (!text.trim()) return {};
    try {
      return JSON.parse(text);
    } catch (error) {
      throw new Error(
        `eBay returned invalid JSON while loading fulfillment details: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
    }
  }

  private normalizeOrder(
    order: any,
    tracking: { trackingCode: string | null; carrier: string | null }
  ): NormalizedOrder {
    const total = order?.pricingSummary?.total || {};
    const buyer = order?.buyer || {};
    const shipTo = order?.fulfillmentStartInstructions?.[0]?.shippingStep?.shipTo || {};
    const address = shipTo?.contactAddress || buyer?.buyerRegistrationAddress?.contactAddress || {};
    const items: NormalizedOrderItem[] = (order?.lineItems || []).map((line: any) => ({
      itemId: line?.lineItemId ? String(line.lineItemId) : null,
      listingId: line?.legacyItemId
        ? String(line.legacyItemId)
        : line?.listing?.legacyItemId
          ? String(line.listing.legacyItemId)
          : null,
      sku: line?.sku ? String(line.sku) : null,
      title: line?.title ? String(line.title) : null,
      quantity: Number(line?.quantity || 1),
      unitPrice: line?.unitPrice?.value != null ? Number(line.unitPrice.value) : null,
      currency: line?.unitPrice?.currency ? String(line.unitPrice.currency) : null,
      raw: line,
    }));

    return {
      marketplace: "EBAY",
      orderId: order?.orderId ? String(order.orderId) : "",
      orderNumber: order?.orderId ? String(order.orderId) : null,
      status: order?.orderFulfillmentStatus ? String(order.orderFulfillmentStatus) : null,
      buyerName: shipTo?.fullName ? String(shipTo.fullName) : buyer?.username ? String(buyer.username) : null,
      buyerEmail: buyer?.email ? String(buyer.email) : null,
      buyerCountry: address?.countryCode ? String(address.countryCode) : null,
      buyerCity: address?.city ? String(address.city) : null,
      buyerState: address?.stateOrProvince ? String(address.stateOrProvince) : null,
      buyerZip: address?.postalCode ? String(address.postalCode) : null,
      trackingCode: tracking.trackingCode,
      carrier: tracking.carrier,
      orderTotal: total?.value != null ? Number(total.value) : null,
      currency: total?.currency ? String(total.currency) : null,
      orderDate: order?.creationDate ? new Date(order.creationDate) : null,
      items,
      raw: order,
    };
  }
}

const TRACKING_KEYS = new Set([
  "trackingnumber",
  "shipmenttrackingnumber",
  "trackingcode",
  "trackingno",
]);
const CARRIER_KEYS = new Set([
  "shippingcarriercode",
  "shippingcarrierused",
  "carrier",
  "carriername",
  "shippingcarrier",
]);

export function mergeEbayTracking(
  ...sources: Array<{ trackingCode: string | null; carrier: string | null }>
): { trackingCode: string | null; carrier: string | null } {
  return {
    trackingCode: sources.find((entry) => entry.trackingCode)?.trackingCode || null,
    carrier: sources.find((entry) => entry.carrier)?.carrier || null,
  };
}

/** Pull tracking from eBay order and shipping-fulfillment payloads, including nested field names. */
export function extractEbayShipmentTracking(source: unknown): { trackingCode: string | null; carrier: string | null } {
  const found = { trackingCode: null as string | null, carrier: null as string | null };
  const visit = (value: unknown) => {
    if (value == null) return;
    if (Array.isArray(value)) {
      for (const entry of value) visit(entry);
      return;
    }
    if (typeof value !== "object") return;
    for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
      const normalized = key.replace(/[\s_-]/g, "").toLowerCase();
      if (!found.trackingCode && typeof child === "string" && child.trim() && TRACKING_KEYS.has(normalized)) {
        found.trackingCode = child.trim();
      }
      if (!found.carrier && typeof child === "string" && child.trim() && CARRIER_KEYS.has(normalized)) {
        found.carrier = child.trim();
      }
      if (child && typeof child === "object") visit(child);
    }
  };
  visit(source);
  return found;
}

function decodeXml(value: string | undefined): string | null {
  return value
    ? value.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").trim()
    : null;
}

function xmlTag(source: string, name: string): string | null {
  return decodeXml(source.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`, "i"))?.[1]);
}

function xmlAmount(source: string, name: string): { value: number | null; currency: string | null } {
  const matched = source.match(new RegExp(`<${name}[^>]*?(?:currencyID="([^"]+)")?[^>]*>([^<]+)<\\/${name}>`, "i"));
  return {
    value: matched?.[2] != null && Number.isFinite(Number(matched[2])) ? Number(matched[2]) : null,
    currency: matched?.[1] || null,
  };
}

/** Parse only ActiveList items from GetMyeBaySelling. Draft/sold/unsold lists are ignored. */
export function parseEbayActiveListings(xml: string): NormalizedListing[] {
  const activeList = xml.match(/<ActiveList[\s\S]*?<\/ActiveList>/i)?.[0] || "";
  if (!activeList) return [];
  const listings: NormalizedListing[] = [];
  for (const match of activeList.matchAll(/<Item>([\s\S]*?)<\/Item>/gi)) {
    const item = match[1];
    const listingId = xmlTag(item, "ItemID");
    if (!listingId) continue;
    const quantitySold = Number(xmlTag(item, "QuantitySold")) || 0;
    const listedQuantity = xmlTag(item, "Quantity") != null ? Number(xmlTag(item, "Quantity")) : null;
    const availableTag = xmlTag(item, "QuantityAvailable");
    const quantity = availableTag != null && Number.isFinite(Number(availableTag))
      ? Number(availableTag)
      : listedQuantity != null ? Math.max(0, listedQuantity - quantitySold) : null;
    const status = xmlTag(item, "ListingStatus") || "ACTIVE";
    const price = xmlAmount(item, "CurrentPrice");
    const image = xmlTag(item, "GalleryURL") || xmlTag(item, "PictureURL");
    listings.push({
      marketplace: "EBAY",
      listingId,
      listingSku: xmlTag(item, "SKU"),
      title: xmlTag(item, "Title"),
      description: null,
      price: price.value,
      currency: price.currency,
      quantity,
      status: status.toUpperCase(),
      listingUrl: xmlTag(item, "ViewItemURL"),
      category: xmlTag(item, "CategoryName"),
      images: image ? [image] : [],
      attributes: {},
      views: Number(xmlTag(item, "HitCount")) || null,
      favorites: Number(xmlTag(item, "WatchCount")) || null,
      orders: quantitySold || null,
      raw: item,
    });
  }
  return listings;
}
