import { httpJson, bearerAuth } from "@/lib/marketplace/http";
import type { MarketplaceConnector, MarketplaceOAuthResult, MarketplaceConnectionContext } from "@/lib/marketplace/connector";
import type {
  NormalizedListing,
  NormalizedOrder,
  NormalizedOrderItem,
  ListingSyncParams,
  OrderSyncParams,
} from "@/lib/marketplace/types";
import {
  getValidAccessToken,
  updateTokens,
  isEncryptionReady,
} from "@/lib/marketplace/oauth";

const SCOPES = [
  "https://api.ebay.com/oauth/api_scope",
  "https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly",
  "https://api.ebay.com/oauth/api_scope/sell.account.readonly",
].join(" ");

function env(name: string): string {
  return (process.env[name] || "").trim();
}

/**
 * eBay calls this value `redirect_uri`, but it is not a URL. It is the
 * OAuth-enabled RuName generated by eBay for the selected environment.
 */
export function getEbayConfigurationError(): string | null {
  const clientId = env("EBAY_CLIENT_ID");
  const clientSecret = env("EBAY_CLIENT_SECRET");
  const ruName = env("EBAY_RU_NAME");

  if (!clientId || !clientSecret || !ruName) {
    return "EBAY_CLIENT_ID, EBAY_CLIENT_SECRET, and EBAY_RU_NAME must be configured.";
  }
  if (/^https?:\/\//i.test(ruName)) {
    return "EBAY_RU_NAME must be the OAuth-enabled eBay RuName, not an Accept/Decline callback URL. Configure the callback URL in eBay's RuName settings.";
  }
  return null;
}

function isSandbox(): boolean {
  return env("EBAY_ENVIRONMENT").toLowerCase() === "sandbox";
}

function bases() {
  const sandbox = isSandbox();
  return {
    sandbox,
    authBase: sandbox ? "https://auth.sandbox.ebay.com" : "https://auth.ebay.com",
    apiBase: sandbox ? "https://api.sandbox.ebay.com" : "https://api.ebay.com",
    findingBase: sandbox ? "https://svcs.sandbox.ebay.com" : "https://svcs.ebay.com",
  };
}

export class EbayConnector implements MarketplaceConnector {
  readonly platform = "EBAY" as const;

  private get clientId() {
    return env("EBAY_CLIENT_ID");
  }
  private get clientSecret() {
    return env("EBAY_CLIENT_SECRET");
  }
  private get ruName() {
    return env("EBAY_RU_NAME");
  }

  async isConfigured(): Promise<boolean> {
    return getEbayConfigurationError() === null;
  }

  async getAuthorizationUrl(state: string): Promise<string> {
    const { authBase } = bases();
    const params = new URLSearchParams({
      client_id: this.clientId,
      response_type: "code",
      redirect_uri: this.ruName,
      scope: SCOPES,
      state,
      // Do not silently reuse an unrelated eBay browser session. Showing the
      // eBay sign-in/consent screen makes account selection explicit.
      prompt: "login",
    });
    return `${authBase}/oauth2/authorize?${params.toString()}`;
  }

  async exchangeAuthorizationCode(code: string): Promise<MarketplaceOAuthResult> {
    if (!(await isEncryptionReady())) {
      throw new Error("Secret encryption key is not configured; cannot store eBay tokens.");
    }
    const { apiBase } = bases();
    const body = new URLSearchParams({
      grant_type: "authorization_code",
      code,
      redirect_uri: this.ruName,
    });
    const basic = Buffer.from(`${this.clientId}:${this.clientSecret}`).toString("base64");
    const data = await httpJson<Record<string, any>>(
      `${apiBase}/identity/v1/oauth2/token`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
          Authorization: `Basic ${basic}`,
        },
        body: body.toString(),
      }
    );
    const tokens = {
      accessToken: data.access_token,
      refreshToken: data.refresh_token,
      expiresAt: data.expires_in ? new Date(Date.now() + data.expires_in * 1000).toISOString() : null,
      scope: data.scope,
    };
    const profile = await this.getAuthenticatedSeller(tokens.accessToken, apiBase);
    const externalAccountId = profile.userId;
    const accountName = profile.username || externalAccountId;
    return {
      externalAccountId,
      accountName,
      tokens,
      shops: [{ externalShopId: externalAccountId, name: accountName }],
    };
  }

  /**
   * The Sell Account API has no /user endpoint. GetUser is the supported
   * authenticated eBay API call for obtaining the account that granted OAuth.
   */
  private async getAuthenticatedSeller(accessToken: string, apiBase: string): Promise<{ userId: string; username: string | null }> {
    const response = await fetch(`${apiBase}/ws/api.dll`, {
      method: "POST",
      headers: {
        "Content-Type": "text/xml",
        "X-EBAY-API-CALL-NAME": "GetUser",
        "X-EBAY-API-COMPATIBILITY-LEVEL": "1231",
        "X-EBAY-API-SITEID": "0",
        "X-EBAY-API-IAF-TOKEN": accessToken,
      },
      body: '<?xml version="1.0" encoding="utf-8"?><GetUserRequest xmlns="urn:ebay:apis:eBLBaseComponents"><DetailLevel>ReturnAll</DetailLevel></GetUserRequest>',
    });
    const xml = await response.text();
    const userId = xml.match(/<UserID>([^<]+)<\/UserID>/i)?.[1]?.trim();

    if (!response.ok || !userId) {
      const ebayMessage = xml.match(/<(?:LongMessage|ShortMessage)>([^<]+)<\/(?:LongMessage|ShortMessage)>/i)?.[1]?.trim();
      throw new Error(ebayMessage || "eBay did not return a seller account ID after authorization.");
    }

    return { userId, username: userId };
  }

  private async getAccessToken(connectionId: string): Promise<string> {
    return getValidAccessToken(connectionId, (tokens) =>
      this.refreshAccessToken(connectionId, tokens.refreshToken!, tokens.scope)
    );
  }

  private async refreshAccessToken(connectionId: string, refreshToken: string, scope?: string | null): Promise<string> {
    const { apiBase } = bases();
    const basic = Buffer.from(`${this.clientId}:${this.clientSecret}`).toString("base64");
    const body = new URLSearchParams({ grant_type: "refresh_token", refresh_token: refreshToken });
    const data = await httpJson<Record<string, any>>(
      `${apiBase}/identity/v1/oauth2/token`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
          Authorization: `Basic ${basic}`,
        },
        body: body.toString(),
      }
    );
    await updateTokens(connectionId, {
      accessToken: data.access_token,
      refreshToken: data.refresh_token || refreshToken,
      expiresAt: data.expires_in ? new Date(Date.now() + data.expires_in * 1000).toISOString() : null,
      scope: data.scope || scope,
    });
    return data.access_token;
  }

  private getHeaders(token: string): Record<string, string> {
    return {
      ...bearerAuth(token),
      Accept: "application/json",
      "Accept-Language": "en-US",
      "Content-Language": "en-US",
    };
  }

  async fetchListings(params: ListingSyncParams, context: MarketplaceConnectionContext): Promise<NormalizedListing[]> {
    const sellerId = context.externalShopId;

    const pageSize = params.limit && params.limit > 0 ? Math.min(params.limit, 50) : 50;
    const page = Math.floor((params.offset || 0) / pageSize) + 1;

    const { findingBase } = bases();
    const url = new URL(`${findingBase}/services/search/FindingAPI/v1`);
    url.searchParams.set("OPERATION-NAME", "findItemsAdvanced");
    url.searchParams.set("SERVICE-VERSION", "1.0.0");
    url.searchParams.set("SECURITY-APPNAME", this.clientId);
    url.searchParams.set("GLOBAL-ID", "EBAY-US");
    url.searchParams.set("RESPONSE-DATA-FORMAT", "JSON");
    url.searchParams.set("REST-PAYLOAD", "");
    url.searchParams.set("sellerId", sellerId);
    url.searchParams.set("paginationInput.entriesPerPage", String(pageSize));
    url.searchParams.set("paginationInput.pageNumber", String(page));

    const data = await httpJson<any>(url.toString(), { method: "GET" });

    const result = data?.findItemsAdvancedResponse?.[0]?.searchResult?.[0];
    const items: any[] = result?.item || [];
    const totalCount = Number(result?.["@count"] || 0);

    console.log(`[ebay] Finding API: seller=${sellerId}, page=${page}, items=${totalCount}`);

    return items.map((item: any) => ({
      ...this.normalizeFindingItem(item),
      marketplaceShopId: context.shopId,
      externalShopId: context.externalShopId,
      shopName: context.shopName,
    }));
  }

  private normalizeFindingItem(item: any): NormalizedListing {
    const price = item?.currentPrice?.[0];
    const condition = item?.condition?.[0];
    const images: string[] = [];
    if (item?.galleryURL?.[0]) images.push(item.galleryURL[0]);
    if (item?.pictureURLSuperSize?.[0]) images.push(item.pictureURLSuperSize[0]);

    return {
      marketplace: "EBAY",
      listingId: String(item?.itemId?.[0] || ""),
      listingSku: item?.sku?.[0] ? String(item.sku[0]) : null,
      title: item?.title?.[0] ? String(item.title[0]) : null,
      description: null,
      price: price?.__value__ != null ? Number(price.__value__) : null,
      currency: price?.__currencyId__ ? String(price.__currencyId__) : null,
      quantity: item?.quantity?.[0] != null ? Number(item.quantity[0]) : null,
      status: item?.listingStatus?.[0] ? String(item.listingStatus[0]) : null,
      listingUrl: item?.viewItemURL?.[0] ? String(item.viewItemURL[0]) : null,
      category: item?.primaryCategory?.[0]?.categoryName?.[0]
        ? String(item.primaryCategory[0].categoryName[0])
        : null,
      images,
      attributes: condition?.[0]?.conditionDisplayName?.[0]
        ? { Condition: String(condition[0].conditionDisplayName[0]) }
        : {},
      views: item?.hitCount?.[0] != null ? Number(item.hitCount[0]) : null,
      favorites: item?.watchCount?.[0] != null ? Number(item.watchCount[0]) : null,
      orders: item?.sellingStatus?.[0]?.quantitySold?.[0] != null
        ? Number(item.sellingStatus[0].quantitySold[0])
        : null,
      raw: item,
    };
  }

  async fetchOrders(params: OrderSyncParams, context: MarketplaceConnectionContext): Promise<NormalizedOrder[]> {
    const token = await this.getAccessToken(context.connectionId);
    const headers = this.getHeaders(token);
    const { apiBase } = bases();

    const pageSize = params.limit && params.limit > 0 ? params.limit : 50;
    const offset = params.offset || 0;
    const filter = params.from ? `creationdate:[${params.from}..]` : undefined;
    const query = new URLSearchParams({ limit: String(pageSize), offset: String(offset) });
    if (filter) query.set("filter", filter);

    const data = await httpJson<{ orders?: any[] }>(
      `${apiBase}/sell/fulfillment/v1/order?${query.toString()}`,
      { headers }
    );

    return (data.orders || []).map((order) => ({
      ...this.normalizeOrder(order),
      marketplaceShopId: context.shopId,
      externalShopId: context.externalShopId,
      shopName: context.shopName,
    }));
  }

  private normalizeOrder(order: any): NormalizedOrder {
    const total = order?.pricingSummary?.total || {};
    const buyer = order?.buyer || {};
    const items: NormalizedOrderItem[] = (order?.lineItems || []).map((line: any) => ({
      itemId: line?.lineItemId ? String(line.lineItemId) : null,
      sku: line?.sku ? String(line.sku) : null,
      title: line?.title ? String(line.title) : null,
      quantity: Number(line?.quantity || 1),
      unitPrice: line?.unitPrice?.value != null ? Number(line.unitPrice.value) : null,
      currency: line?.unitPrice?.currency ? String(line.unitPrice.currency) : null,
      raw: line,
    }));

    return {
      marketplace: "EBAY",
      orderId: order?.orderId ? String(order.orderId) : "",
      orderNumber: order?.orderId ? String(order.orderId) : null,
      status: order?.orderFulfillmentStatus ? String(order.orderFulfillmentStatus) : null,
      buyerName: buyer?.username ? String(buyer.username) : null,
      buyerEmail: buyer?.email ? String(buyer.email) : null,
      orderTotal: total?.value != null ? Number(total.value) : null,
      currency: total?.currency ? String(total.currency) : null,
      orderDate: order?.creationDate ? new Date(order.creationDate) : null,
      items,
      raw: order,
    };
  }
}
