import { httpJson, bearerAuth } from "@/lib/marketplace/http";
import type { MarketplaceConnector, MarketplaceOAuthResult, MarketplaceConnectionContext } from "@/lib/marketplace/connector";
import type {
  NormalizedListing,
  NormalizedOrder,
  NormalizedOrderItem,
  ListingSyncParams,
  OrderSyncParams,
} from "@/lib/marketplace/types";
import {
  getValidAccessToken,
  updateTokens,
  isEncryptionReady,
} from "@/lib/marketplace/oauth";

const SCOPES = [
  "https://api.ebay.com/oauth/api_scope",
  "https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly",
  "https://api.ebay.com/oauth/api_scope/sell.account.readonly",
].join(" ");

function env(name: string): string {
  return (process.env[name] || "").trim();
}

/**
 * eBay calls this value `redirect_uri`, but it is not a URL. It is the
 * OAuth-enabled RuName generated by eBay for the selected environment.
 */
export function getEbayConfigurationError(): string | null {
  const clientId = env("EBAY_CLIENT_ID");
  const clientSecret = env("EBAY_CLIENT_SECRET");
  const ruName = env("EBAY_RU_NAME");

  if (!clientId || !clientSecret || !ruName) {
    return "EBAY_CLIENT_ID, EBAY_CLIENT_SECRET, and EBAY_RU_NAME must be configured.";
  }
  if (/^https?:\/\//i.test(ruName)) {
    return "EBAY_RU_NAME must be the OAuth-enabled eBay RuName, not an Accept/Decline callback URL. Configure the callback URL in eBay's RuName settings.";
  }
  return null;
}

function isSandbox(): boolean {
  return env("EBAY_ENVIRONMENT").toLowerCase() === "sandbox";
}

function bases() {
  const sandbox = isSandbox();
  return {
    sandbox,
    authBase: sandbox ? "https://auth.sandbox.ebay.com" : "https://auth.ebay.com",
    apiBase: sandbox ? "https://api.sandbox.ebay.com" : "https://api.ebay.com",
    findingBase: sandbox ? "https://svcs.sandbox.ebay.com" : "https://svcs.ebay.com",
  };
}

export class EbayConnector implements MarketplaceConnector {
  readonly platform = "EBAY" as const;

  private get clientId() {
    return env("EBAY_CLIENT_ID");
  }
  private get clientSecret() {
    return env("EBAY_CLIENT_SECRET");
  }
  private get ruName() {
    return env("EBAY_RU_NAME");
  }

  async isConfigured(): Promise<boolean> {
    return getEbayConfigurationError() === null;
  }

  async getAuthorizationUrl(state: string): Promise<string> {
    const { authBase } = bases();
    const params = new URLSearchParams({
      client_id: this.clientId,
      response_type: "code",
      redirect_uri: this.ruName,
      scope: SCOPES,
      state,
      // Do not silently reuse an unrelated eBay browser session. Showing the
      // eBay sign-in/consent screen makes account selection explicit.
      prompt: "login",
    });
    return `${authBase}/oauth2/authorize?${params.toString()}`;
  }

  async exchangeAuthorizationCode(code: string): Promise<MarketplaceOAuthResult> {
    if (!(await isEncryptionReady())) {
      throw new Error("Secret encryption key is not configured; cannot store eBay tokens.");
    }
    const { apiBase } = bases();
    const body = new URLSearchParams({
      grant_type: "authorization_code",
      code,
      redirect_uri: this.ruName,
    });
    const basic = Buffer.from(`${this.clientId}:${this.clientSecret}`).toString("base64");
    const data = await httpJson<Record<string, any>>(
      `${apiBase}/identity/v1/oauth2/token`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
          Authorization: `Basic ${basic}`,
        },
        body: body.toString(),
      }
    );
    const tokens = {
      accessToken: data.access_token,
      refreshToken: data.refresh_token,
      expiresAt: data.expires_in ? new Date(Date.now() + data.expires_in * 1000).toISOString() : null,
      scope: data.scope,
    };
    const profile = await this.getAuthenticatedSeller(tokens.accessToken, apiBase);
    const externalAccountId = profile.userId;
    const accountName = profile.username || externalAccountId;
    return {
      externalAccountId,
      accountName,
      tokens,
      shops: [{ externalShopId: externalAccountId, name: accountName }],
    };
  }

  /**
   * The Sell Account API has no /user endpoint. GetUser is the supported
   * authenticated eBay API call for obtaining the account that granted OAuth.
   */
  private async getAuthenticatedSeller(accessToken: string, apiBase: string): Promise<{ userId: string; username: string | null }> {
    const response = await fetch(`${apiBase}/ws/api.dll`, {
      method: "POST",
      headers: {
        "Content-Type": "text/xml",
        "X-EBAY-API-CALL-NAME": "GetUser",
        "X-EBAY-API-COMPATIBILITY-LEVEL": "1231",
        "X-EBAY-API-SITEID": "0",
        "X-EBAY-API-IAF-TOKEN": accessToken,
      },
      body: '<?xml version="1.0" encoding="utf-8"?><GetUserRequest xmlns="urn:ebay:apis:eBLBaseComponents"><DetailLevel>ReturnAll</DetailLevel></GetUserRequest>',
    });
    const xml = await response.text();
    const userId = xml.match(/<UserID>([^<]+)<\/UserID>/i)?.[1]?.trim();

    if (!response.ok || !userId) {
      const ebayMessage = xml.match(/<(?:LongMessage|ShortMessage)>([^<]+)<\/(?:LongMessage|ShortMessage)>/i)?.[1]?.trim();
      throw new Error(ebayMessage || "eBay did not return a seller account ID after authorization.");
    }

    return { userId, username: userId };
  }

  private async getAccessToken(connectionId: string): Promise<string> {
    return getValidAccessToken(connectionId, (tokens) =>
      this.refreshAccessToken(connectionId, tokens.refreshToken!, tokens.scope)
    );
  }

  private async refreshAccessToken(connectionId: string, refreshToken: string, scope?: string | null): Promise<string> {
    const { apiBase } = bases();
    const basic = Buffer.from(`${this.clientId}:${this.clientSecret}`).toString("base64");
    const body = new URLSearchParams({ grant_type: "refresh_token", refresh_token: refreshToken });
    const data = await httpJson<Record<string, any>>(
      `${apiBase}/identity/v1/oauth2/token`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
          Authorization: `Basic ${basic}`,
        },
        body: body.toString(),
      }
    );
    await updateTokens(connectionId, {
      accessToken: data.access_token,
      refreshToken: data.refresh_token || refreshToken,
      expiresAt: data.expires_in ? new Date(Date.now() + data.expires_in * 1000).toISOString() : null,
      scope: data.scope || scope,
    });
    return data.access_token;
  }

  private getHeaders(token: string): Record<string, string> {
    return {
      ...bearerAuth(token),
      Accept: "application/json",
      "Accept-Language": "en-US",
      "Content-Language": "en-US",
    };
  }

  async fetchListings(params: ListingSyncParams, context: MarketplaceConnectionContext): Promise<NormalizedListing[]> {
    const token = await this.getAccessToken(context.connectionId);
    const pageSize = params.limit && params.limit > 0 ? Math.min(params.limit, 100) : 100;
    const page = Math.floor((params.offset || 0) / pageSize) + 1;
    const { apiBase } = bases();
    const xml = await this.callTradingApi(
      "GetMyeBaySelling",
      token,
      apiBase,
      `<GetMyeBaySellingRequest xmlns="urn:ebay:apis:eBLBaseComponents"><DetailLevel>ReturnAll</DetailLevel><ActiveList><Include>true</Include><Pagination><EntriesPerPage>${pageSize}</EntriesPerPage><PageNumber>${page}</PageNumber></Pagination></ActiveList></GetMyeBaySellingRequest>`
    );
    const items = this.parseTradingItems(xml);
    console.log(`[ebay] GetMyeBaySelling: shop=${context.externalShopId}, page=${page}, items=${items.length}`);

    return items.map((item) => ({
      ...item,
      marketplaceShopId: context.shopId,
      externalShopId: context.externalShopId,
      shopName: context.shopName,
    }));
  }

  private async callTradingApi(callName: string, accessToken: string, apiBase: string, body: string): Promise<string> {
    const response = await fetch(`${apiBase}/ws/api.dll`, {
      method: "POST",
      headers: {
        "Content-Type": "text/xml",
        "X-EBAY-API-CALL-NAME": callName,
        "X-EBAY-API-COMPATIBILITY-LEVEL": "1231",
        "X-EBAY-API-SITEID": "0",
        "X-EBAY-API-IAF-TOKEN": accessToken,
      },
      body: `<?xml version="1.0" encoding="utf-8"?>${body}`,
    });
    const xml = await response.text();
    const ebayMessage = xml.match(/<(?:LongMessage|ShortMessage)>([^<]+)<\/(?:LongMessage|ShortMessage)>/i)?.[1]?.trim();
    if (!response.ok || /<Ack>(?:Failure|PartialFailure)<\/Ack>/i.test(xml)) {
      throw new Error(ebayMessage || `eBay ${callName} failed (HTTP ${response.status}).`);
    }
    return xml;
  }

  private parseTradingItems(xml: string): NormalizedListing[] {
    const decode = (value: string | undefined): string | null => value
      ? value.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").trim()
      : null;
    const tag = (source: string, name: string): string | null => decode(source.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`, "i"))?.[1]);
    const amount = (source: string, name: string): { value: number | null; currency: string | null } => {
      const matched = source.match(new RegExp(`<${name}[^>]*?(?:currencyID="([^"]+)")?[^>]*>([^<]+)<\\/${name}>`, "i"));
      return { value: matched?.[2] != null && Number.isFinite(Number(matched[2])) ? Number(matched[2]) : null, currency: matched?.[1] || null };
    };
    const listings: NormalizedListing[] = [];
    for (const match of xml.matchAll(/<Item>([\s\S]*?)<\/Item>/gi)) {
      const item = match[1];
      const price = amount(item, "CurrentPrice");
      const listingId = tag(item, "ItemID");
      if (!listingId) continue;
      const image = tag(item, "GalleryURL") || tag(item, "PictureURL");
      listings.push({
        marketplace: "EBAY",
        listingId,
        listingSku: tag(item, "SKU"),
        title: tag(item, "Title"),
        description: null,
        price: price.value,
        currency: price.currency,
        quantity: Number(tag(item, "Quantity")) || null,
        status: tag(item, "ListingStatus") || "ACTIVE",
        listingUrl: tag(item, "ViewItemURL"),
        category: tag(item, "CategoryName"),
        images: image ? [image] : [],
        attributes: {},
        views: Number(tag(item, "HitCount")) || null,
        favorites: Number(tag(item, "WatchCount")) || null,
        orders: Number(tag(item, "QuantitySold")) || null,
        raw: item,
      });
    }
    return listings;
  }

  async fetchOrders(params: OrderSyncParams, context: MarketplaceConnectionContext): Promise<NormalizedOrder[]> {
    const token = await this.getAccessToken(context.connectionId);
    const headers = this.getHeaders(token);
    const { apiBase } = bases();

    const pageSize = params.limit && params.limit > 0 ? params.limit : 50;
    const offset = params.offset || 0;
    const filter = params.from ? `creationdate:[${params.from}..]` : undefined;
    const query = new URLSearchParams({ limit: String(pageSize), offset: String(offset) });
    if (filter) query.set("filter", filter);

    const data = await httpJson<{ orders?: any[] }>(
      `${apiBase}/sell/fulfillment/v1/order?${query.toString()}`,
      { headers }
    );

    // Fulfillment's order search is intrinsically limited to the seller who
    // granted this connection's OAuth token; it cannot return another shop's
    // orders. Load package details separately so tracking is kept current.
    return Promise.all((data.orders || []).map(async (order) => {
      const tracking = await this.getTrackingDetails(order?.orderId, headers, apiBase);
      return {
        ...this.normalizeOrder(order, tracking),
        marketplaceShopId: context.shopId,
        externalShopId: context.externalShopId,
        shopName: context.shopName,
      };
    }));
  }

  private async getTrackingDetails(
    orderId: unknown,
    headers: Record<string, string>,
    apiBase: string
  ): Promise<{ trackingCode: string | null; carrier: string | null }> {
    const id = String(orderId || "").trim();
    if (!id) return { trackingCode: null, carrier: null };

    try {
      const data = await httpJson<{ fulfillments?: Array<{ trackingNumber?: string; shippingCarrierCode?: string }> }>(
        `${apiBase}/sell/fulfillment/v1/order/${encodeURIComponent(id)}/shipping_fulfillment`,
        { headers }
      );
      const fulfillment = data.fulfillments?.find((entry) => entry.trackingNumber) || data.fulfillments?.[0];
      return {
        trackingCode: fulfillment?.trackingNumber ? String(fulfillment.trackingNumber) : null,
        carrier: fulfillment?.shippingCarrierCode ? String(fulfillment.shippingCarrierCode) : null,
      };
    } catch (error) {
      // An order may not have been shipped yet. Do not fail its complete order
      // sync merely because eBay has no fulfillment record at this point.
      console.warn(`[ebay] Could not load tracking for order ${id}:`, error);
      return { trackingCode: null, carrier: null };
    }
  }

  private normalizeOrder(
    order: any,
    tracking: { trackingCode: string | null; carrier: string | null }
  ): NormalizedOrder {
    const total = order?.pricingSummary?.total || {};
    const buyer = order?.buyer || {};
    const shipTo = order?.fulfillmentStartInstructions?.[0]?.shippingStep?.shipTo || {};
    const address = shipTo?.contactAddress || buyer?.buyerRegistrationAddress?.contactAddress || {};
    const items: NormalizedOrderItem[] = (order?.lineItems || []).map((line: any) => ({
      itemId: line?.lineItemId ? String(line.lineItemId) : null,
      sku: line?.sku ? String(line.sku) : null,
      title: line?.title ? String(line.title) : null,
      quantity: Number(line?.quantity || 1),
      unitPrice: line?.unitPrice?.value != null ? Number(line.unitPrice.value) : null,
      currency: line?.unitPrice?.currency ? String(line.unitPrice.currency) : null,
      raw: line,
    }));

    return {
      marketplace: "EBAY",
      orderId: order?.orderId ? String(order.orderId) : "",
      orderNumber: order?.orderId ? String(order.orderId) : null,
      status: order?.orderFulfillmentStatus ? String(order.orderFulfillmentStatus) : null,
      buyerName: shipTo?.fullName ? String(shipTo.fullName) : buyer?.username ? String(buyer.username) : null,
      buyerEmail: buyer?.email ? String(buyer.email) : null,
      buyerCountry: address?.countryCode ? String(address.countryCode) : null,
      buyerCity: address?.city ? String(address.city) : null,
      buyerState: address?.stateOrProvince ? String(address.stateOrProvince) : null,
      buyerZip: address?.postalCode ? String(address.postalCode) : null,
      trackingCode: tracking.trackingCode,
      carrier: tracking.carrier,
      orderTotal: total?.value != null ? Number(total.value) : null,
      currency: total?.currency ? String(total.currency) : null,
      orderDate: order?.creationDate ? new Date(order.creationDate) : null,
      items,
      raw: order,
    };
  }
}
