ALTER TABLE "SalesReturn" ADD COLUMN "taxableAmount" REAL NOT NULL DEFAULT 0;
ALTER TABLE "SalesReturn" ADD COLUMN "igst" REAL NOT NULL DEFAULT 0;
ALTER TABLE "SalesReturn" ADD COLUMN "cgst" REAL NOT NULL DEFAULT 0;
ALTER TABLE "SalesReturn" ADD COLUMN "sgst" REAL NOT NULL DEFAULT 0;
ALTER TABLE "SalesReturn" ADD COLUMN "totalTax" REAL NOT NULL DEFAULT 0;
ALTER TABLE "SalesReturn" ADD COLUMN "totalAmount" REAL NOT NULL DEFAULT 0;

ALTER TABLE "CreditNote" ADD COLUMN "taxableAmount" REAL NOT NULL DEFAULT 0;
ALTER TABLE "CreditNote" ADD COLUMN "igst" REAL NOT NULL DEFAULT 0;
ALTER TABLE "CreditNote" ADD COLUMN "cgst" REAL NOT NULL DEFAULT 0;
ALTER TABLE "CreditNote" ADD COLUMN "sgst" REAL NOT NULL DEFAULT 0;
ALTER TABLE "CreditNote" ADD COLUMN "totalTax" REAL NOT NULL DEFAULT 0;
